[workspace]
members = [
    "crates/utils",
    "crates/common",
    "crates/common/block-macros",
    "crates/worldgen",
    "crates/physics",
    "crates/protocol",
    "crates/server",
    "crates/client",
]

[profile.release]
debug = true
