[package]
name = "voltzui"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
utils = { path = "../utils" }

glam = "0.11"
tiny-skia =  "0.2"
fontdue = "0.4"
stretch = "0.3"
ahash = "0.6"
