[package]
name = "utils"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
bumpalo = { path = "../../../bumpalo" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
rand = "0.7"
rand_pcg = "0.2"
