[package]
name = "common"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
utils = { path = "../utils" }
block-macros = { path = "./block-macros" }
once_cell = "1"
ahash = "0.5"
thiserror = "1"
uuid = { version = "0.8", features = ["v4"] }
